name: Main

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Try Out Expressions
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Error
        run: |
          cat nope
      - name: Handle fail
        if: failure()
        run: |
          echo "Failed to checkout but that's OK..."
      - name: Success
        if: success()
        run: |
          echo "This went well..."
      - name: Is this gonna run?
        run: |
          echo "Let' see what this does..."
          
          
      