name: Main

on:
  release:
    types: [published]
  push:
    branches:
      - main

jobs:
  main:
    name: Deploy
    runs-on: ubuntu-20.04

    steps:
      - name: Print event name
        run: echo "${{ github.event_name }}"

